//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeServis
    {
        public int Id { get; set; }
        public int IdEmployee { get; set; }
        public int IdService { get; set; }
    
        public virtual EmployeeData EmployeeData { get; set; }
        public virtual Service Service { get; set; }
    }
}
